### ISSUE TITLE
Start build/deploy

### ISSUE THREAD

**Issue by ringods** [wercker/api#1]
In order to construct build/deploy pipelines, I would like a downstream build or deploy to start when a current build or deploy is succesfull. The API should allow to start builds or deploys of an application.

Once this is in place in the API, I can implement a Wercker step to start the build or deploy.

**Comment by hatchan** [comment]
Currently we're going to focus on readonly data. Being able to trigger builds, and other action is something which will be worked on after this.

Thanks for the feedback :+1:

**Comment by ringods** [comment]
Any progress on this one?

**Comment by hatchan** [comment]
We're almost done with triggering a build. Will be released next week.

**Comment by ringods** [comment]
Double :+1:

**Comment by ringods** [comment]
@hatchan will Wercker release a step to trigger a build for another project? This results in pipelines over projects...

**Comment by hatchan** [comment]
Forgot to close this item, so hope you already read the announcement: http://blog.wercker.com/2015/06/23/Trigger-builds-with-the-api.html

Currently we do not have a step, but I think I already saw someone else create a trigger build step.
