### ISSUE TITLE
 Cache directory cleared

### ISSUE THREAD

**Issue by peterturowskij** [wercker/api#12]
Cache directory seems to be cleared in between build and deploy stages. Is it by design?

Reason asking, in case deploy steps make use of artifacts already loaded while build process, it takes extra time and traffic

**Comment by mwhooker** [comment]
@peterturowskij Thanks for the report! The behavior for now is a bit bugged, but I'm working on it today. I'll close this ticket when it's fixed.

**Comment by peterturowskij** [comment]
Thank you

**Comment by mwhooker** [comment]
@peterturowskij should be fixed now. Please re-open if you have any more issues with it.
