### ISSUE TITLE
Rest API. Trigger Parameters

### ISSUE THREAD

**Issue by peterturowskij** [wercker/api#8]
Could be worth having trigger to accept parameters later exposed and available as environment variables.

POST /api/v3/builds/
{
++ "parameters" : [
++    "paramA" : "valueA" ]
}

echo $paramA

**Comment by hatchan** [comment]
Thanks for the suggestion. This was something which we already started work on. It should be released later this week.

**Comment by peterturowskij** [comment]
Great, thank you. Could you please also give a comment on issue#6

**Comment by peterturowskij** [comment]
Any progress on this one?

**Comment by hirakiuc** [comment]
+1

**Comment by hatchan** [comment]
This has been released http://blog.wercker.com/2015/07/30/env-vars.html Forgot to mention it in in this post, sorry.
